import { ImageSourcePropType } from "react-native";

export interface FoodSchema {
  percent: number;
  foods: FoodUpgrades;
}
export const FoodUpgradesItems: FoodUpgrades = {
  Крупа: [
    {
      name: "Гречка",
      price: 10,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 1,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Рис",
      price: 100,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 10,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Перловка",
      price: 500,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 50,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Кукуруза",
      price: 2000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 150,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Пшено",
      price: 5000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 400,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "4 в 1: Гречка, Перловка, Кукуруза, Пшено",
      price: 15000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 1500,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Рис С индейкой от Димы Лепского",
      price: 25000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 2000,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Рис с курицей от Вики",
      price: 25000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 2000,
      debuff: 0,
      buy_times: 0,
    },
  ],
  Мясо: [
    {
      name: "Говядина",
      price: 1000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 100,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Курица",
      price: 2000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 250,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Свинина",
      price: 5000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 750,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Шашлык",
      price: 17500,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 1500,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Сосиски в угле",
      price: 30000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 2500,
      debuff: 0,
      buy_times: 0,
    },
  ],
  Суп: [
    {
      name: "Куриный суп",
      price: 350,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 200,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Гороховый суп",
      price: 565,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 325,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Суп с перловкой",
      price: 1400,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 500,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Суп с клецками",
      price: 1750,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 625,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Доширак",
      price: 3500,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 1000,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Острый японский суп",
      price: 10000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 1750,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Суп, который уже неделю ешь",
      price: 30000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 3500,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Суп, который уже месяц ешь",
      price: 35000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 4000,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Суп, который уже год ешь",
      price: 40000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 4500,
      debuff: 0,
      buy_times: 0,
    },
  ],
  Плов: [
    {
      name: "Обычный плов",
      price: 10000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 1000,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Редкий плов",
      price: 20000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 2000,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Эпический плов",
      price: 30000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 3000,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Легендарный плов",
      price: 40000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 4000,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Элитный плов",
      price: 50000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 5000,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Татарский плов",
      price: 60000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 6000,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Плов на раздаче в Волгограде",
      price: 70000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 7000,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Казан плова",
      price: 100000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 10000,
      debuff: 0,
      buy_times: 0,
    },
  ],
  Десерт: [
    {
      name: "Американец",
      price: 65,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 20,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Бедный еврей",
      price: 75,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 30,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Хохол",
      price: 85,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 40,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Энжелатто",
      price: 170,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 50,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Чудо с шоколадом и бананом",
      price: 200,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 55,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Чудо с шоколадом",
      price: 250,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 65,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Чиорио",
      price: 300,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 85,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Кроканд",
      price: 500,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 100,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Миливэй",
      price: 550,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 110,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Бэйбифокс",
      price: 600,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 120,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Сладкий подарок",
      price: 2000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 350,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Китайские сладости",
      price: 2500,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 400,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Китайские сладости в Хабаровске",
      price: 3000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 450,
      debuff: 0,
      buy_times: 0,
    },
  ],
  Фикспрайс: [
    {
      name: "Микродошик",
      price: 10,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 1,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Дошик",
      price: 20,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 2,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Макродошик",
      price: 30,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 3,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Орешки",
      price: 50,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 5,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Начос",
      price: 100,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 10,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Лимонад",
      price: 130,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 13,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Горилла",
      price: 1500,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 70,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "5G",
      price: 2500,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 250,
      debuff: 0,
      buy_times: 0,
    },
  ],
  Покурить: [
    {
      name: "Favostick",
      price: 1000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 100,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Passito 2",
      price: 2000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 200,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Charon baby",
      price: 3000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 300,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Manto plus",
      price: 4000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 400,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Passito mini",
      price: 5000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 500,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Vaporesso Gen Air 40",
      price: 6000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 600,
      debuff: 0,
      buy_times: 0,
    },
    {
      name: "Aegis boost 2",
      price: 100000,
      imgSrc: require("../../../../../assets/favicon.png"),
      profit: 10000,
      debuff: 0,
      buy_times: 0,
    },
  ],
};

export type FoodUpgrades = {
  Крупа: FoodItem[];
  Мясо: FoodItem[];
  Суп: FoodItem[];
  Плов: FoodItem[];
  Десерт: FoodItem[];
  Фикспрайс: FoodItem[];
  Покурить: FoodItem[];
};

export interface FoodItem {
  name: string;
  price: number;
  imgSrc: ImageSourcePropType;
  profit: number;
  debuff: number;
  buy_times: number;
}
